[package]
name = "cert_gen_extract"
version = "0.1.0"
authors = ["Andrew Jandl <akjandl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
glob = "0.3.0"
calamine = "0.16.1"
